name: simpleSayHello
on:
  push:
    branches:
      - main
#   workflow_dispatch:
permissions:
  contents: read
jobs:
  sayhello:
    name: sayhello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Run python script
        run: |
            cd  ../../
            python sayHello.py